name: tf check
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build_terraform_validate:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
 
      - name: Terraform Init
        run: terraform init

      - name: Format Packer template
        run: |
          terraform fmt . -check -diff .
          if [ $? -ne 0 ]; then
            echo "Terraform templates need formatting. Run 'terraform fmt .' locally and push the changes."
            exit 1
          fi
 
      - name: Terraform Validate
        run: terraform validate